import { z } from "zod";

const UsernameSchema = z
  .string()
  .min(3, "Username must be at least 3 characters")
  .max(30, "Username cannot exceed 30 characters")
  .regex(
    /^[\p{L}\p{N}]+([\p{L}\p{N} ]+)*$/u,
    "Username must contain only letters, numbers, and spaces",
  )
  .trim()
  .transform((s) => s.trim())
  .refine((username) => !reservedUsername(username), {
    message: "This username is reserved",
  });

export default UsernameSchema;

const reservedDevUsernames = ["admin", "root", "system", "support", "null"];
const reservedUsernamesStartingWith = ["favicon", "manifest"];
const reservedUsernames = [
  "account",
  "administracao",
  "administrador",
  "administradora",
  "administradores",
  "administrator",
  "afiliado",
  "afiliados",
  "ajuda",
  "alerta",
  "alertas",
  "all",
  "analytics",
  "anonymous",
  "anunciar",
  "anuncie",
  "anuncio",
  "anuncios",
  "api",
  "app",
  "apps",
  "autenticacao",
  "auth",
  "authentication",
  "autorizacao",
  "avatar",
  "backup",
  "banner",
  "banners",
  "beta",
  "blog",
  "cadastrar",
  "cadastro",
  "carrinho",
  "categoria",
  "categorias",
  "categories",
  "category",
  "ceo",
  "cfo",
  "checkout",
  "classificados",
  "comentario",
  "comentarios",
  "compartilhada",
  "compartilhadas",
  "compartilhado",
  "compartilhados",
  "comunidade",
  "comunidades",
  "config",
  "configuracao",
  "configuracoes",
  "configurar",
  "configure",
  "conta",
  "contas",
  "contato",
  "contatos",
  "content",
  "conteudos",
  "contrato",
  "convite",
  "convites",
  "create",
  "criar",
  "css",
  "cto",
  "cultura",
  "curso",
  "cursos",
  "dados",
  "dashboard",
  "desconectar",
  "descricao",
  "description",
  "deslogar",
  "diretrizes",
  "discussao",
  "docs",
  "documentacao",
  "download",
  "downloads",
  "draft",
  "edit",
  "editar",
  "editor",
  "email",
  "estatisticas",
  "eu",
  "faq",
  "features",
  "gerente",
  "grupo",
  "grupos",
  "guest",
  "guidelines",
  "hoje",
  "imagem",
  "imagens",
  "init",
  "interface",
  "licenca",
  "log",
  "login",
  "logout",
  "loja",
  "me",
  "membership",
  "moderacao",
  "moderador",
  "moderadora",
  "moderadoras",
  "moderadores",
  "museu",
  "news",
  "newsletter",
  "newsletters",
  "notificacoes",
  "notification",
  "notifications",
  "ontem",
  "pagina",
  "password",
  "patrocinada",
  "patrocinadas",
  "patrocinado",
  "patrocinados",
  "perfil",
  "pesquisa",
  "popular",
  "post",
  "postar",
  "posts",
  "preferencias",
  "promoted",
  "promovida",
  "promovidas",
  "promovido",
  "promovidos",
  "public",
  "publicar",
  "publish",
  "rascunho",
  "recentes",
  "register",
  "registration",
  "regras",
  "relatorio",
  "relatorios",
  "replies",
  "reply",
  "resetar-senha",
  "resetar",
  "resposta",
  "respostas",
  "root",
  "rootuser",
  "rss",
  "sair",
  "senha",
  "sobre",
  "sponsored",
  "status",
  "sudo",
  "superuser",
  "suporte",
  "support",
  "swr",
  "sysadmin",
  "tabnew",
  "tabnews",
  "tag",
  "tags",
  "termos-de-uso",
  "termos",
  "terms",
  "toc",
  "todos",
  "trending",
  "upgrade",
  "username",
  "users",
  "usuario",
  "usuarios",
  "va",
  "vagas",
  "videos",
];

function reservedUsername(username: string) {
  return (
    reservedDevUsernames.includes(username.toLowerCase()) ||
    reservedUsernames.includes(username.toLowerCase()) ||
    reservedUsernamesStartingWith.find((reserved) =>
      username.toLowerCase().startsWith(reserved),
    )
  );
}
